name: Development Deployment

on:
  push:
    branches:
      - 'development'

env:
  PROJECT_NAME: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
  CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
  DOCKER_IMAGE: ${{ secrets.GOOGLE_DOCKER_IMAGE }}
  REGION: ${{ secrets.GOOGLE_REGION }}
  SERVICE: ${{ secrets.GOOGLE_CLOUD_RUN_SERVICE }}

jobs:
  # build:
  #   name: "Build"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup authorization on Google Cloud Platform
  #       uses: 'google-github-actions/auth@v2'
  #       with:
  #         credentials_json: ${{ env.CREDENTIALS }}

  #     - name: Setup docker on Google Cloud Platform
  #       run: gcloud auth configure-docker $REGION-docker.pkg.dev
      
  #     - name: Setup SDK on Google Cloud Platform
  #       uses: google-github-actions/setup-gcloud@v2
          
  #     - name: Build Docker Image
  #       run: docker build -t $DOCKER_IMAGE:dev .
        
  #     - name: Push Docker Image
  #       run: docker push $DOCKER_IMAGE:dev
  
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup authorization on Google Cloud Platform
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ env.CREDENTIALS }}
      
      - name: Cloud Run Deploy
        run: |-
          gcloud run deploy $SERVICE \
          --project 'website-development' \
          --region $REGION \
          --image $DOCKER_IMAGE:dev \
          --account $GOOGLE_SERVICE_ACCOUNT \
          --quiet